//
//  UITabViewController.swift
//  VKApp
//
//  Created by User on 01.02.2021.
//

import UIKit

var friends: [User] = []
var groups: [Group] = []
var news: [NewsPost] = []

class UITabViewController: UITabBarController {

    override func viewDidLoad() {
        super.viewDidLoad()

        updateFrindsList()
        updateNews()
        
        for index in 0...10 {
            let group = Group(name: "Group \(index)", description: "Just a simple group as any other", avatar: UIImage(named: "groupsAvatar")!, userIn: false, likes: index * 4, liked: false)
            groups.append(group)
        }
        
    }
    
    func updateNews () {
        
        var images: [UIImage] = []
        images.removeAll()
        
        images.append(UIImage(named: "news_4")!)
        images.append(UIImage(named: "news_1")!)
        images.append(UIImage(named: "news_2")!)
        images.append(UIImage(named: "news_3")!)
        images.append(UIImage(named: "news_2")!)
        
        
        news.append(NewsPost(text: "First News", images: images, likesCount: 10, isLiked: false, viewsCount: 15, repostsCount: 10, commentsCount: 3 ))
        
        images.remove(at: 2)
        
        news.append(NewsPost(text: "Second News", images: images, likesCount: 20, isLiked: true, viewsCount: 35, repostsCount: 10, commentsCount: 3))
        news.append(NewsPost(text: "Third News", images: images, likesCount: 12, isLiked: false, viewsCount: 15, repostsCount: 10, commentsCount: 3))
        
        images.remove(at: 0)
        images.remove(at: 0)
        
        news.append(NewsPost(text: "One more news to make it right", images: images, likesCount: 5, isLiked: true, viewsCount: 35, repostsCount: 10, commentsCount: 3))
        news.append(NewsPost(text: "One more news to make it right", images: images, likesCount: 5, isLiked: true, viewsCount: 35, repostsCount: 10, commentsCount: 3))
        news.append(NewsPost(text: "One more news to make it right", images: images, likesCount: 5, isLiked: true, viewsCount: 35, repostsCount: 10, commentsCount: 3))
        news.append(NewsPost(text: "One more news to make it right", images: images, likesCount: 5, isLiked: true, viewsCount: 35, repostsCount: 10, commentsCount: 3))
        
        news.append(NewsPost(text: "One more news to make it right", images: images, likesCount: 5, isLiked: true, viewsCount: 35, repostsCount: 10, commentsCount: 3))
        news.append(NewsPost(text: "One more news to make it right", images: images, likesCount: 5, isLiked: true, viewsCount: 35, repostsCount: 10, commentsCount: 3))
        news.append(NewsPost(text: "One more news to make it right", images: images, likesCount: 5, isLiked: true, viewsCount: 35, repostsCount: 10, commentsCount: 3))
        
    }

    func updateFrindsList () {
        
        var imagesList: [UIImage] = []
        
        for index in 1...11 {
            imagesList.append(UIImage(named: "f_\(index)")!)
        }
        
        friends.append(User(name: "Ярослав", surname: "Воробьёв", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Еремей ", surname: "Кулаков", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Йозеф ", surname: "Павлов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Харитон ", surname: "Соболев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Зуфар ", surname: "Михайлов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Ждан ", surname: "Самсонов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Харитон ", surname: "Тарасюк", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Устин ", surname: "Петренко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Рафаил ", surname: "Шумейко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Йомер ", surname: "Кобзар", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Платон ", surname: "Карпенко-Карый", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Йозеф ", surname: "Федосеев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Шамиль ", surname: "Королёв", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Феликс ", surname: "Иващенко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Харитон ", surname: "Соколов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Яромир ", surname: "Бердник", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Шарль ", surname: "Лазарев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Лев ", surname: "Бобров", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Иван ", surname: "Спивак", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Устин ", surname: "Фёдоров", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Тимофей ", surname: "Павленко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Богдан ", surname: "Милославский", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Тарас ", surname: "Зыков", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Цефас ", surname: "Дементьев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Еремей ", surname: "Харитонов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Ждан ", surname: "Маслов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Остин ", surname: "Притула", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Юлиан ", surname: "Коровяк", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Влад ", surname: "Ситников", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Устин ", surname: "Ерёменко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Чеслав ", surname: "Овчинников", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Роберт ", surname: "Казаков", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Яромир ", surname: "Лапин", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Павел ", surname: "Повалий", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Константин ", surname: "Белов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Карен ", surname: "Фадеев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Зуфар ", surname: "Устинов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Орландо ", surname: "Макаров", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Харитон ", surname: "Некрасов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Филипп ", surname: "Андреев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Ждан ", surname: "Темченко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Егор ", surname: "Лыткин", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Феликс ", surname: "Моисеенко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Михаил ", surname: "Петухов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Остап ", surname: "Власов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Стефан ", surname: "Зварыч", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Роберт ", surname: "Смирнов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Еремей ", surname: "Киселёв", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Мирослав ", surname: "Одинцов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Платон ", surname: "Майборода", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Йозеф ", surname: "Сусаренко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Чеслав ", surname: "Грабчак", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Йозеф ", surname: "Одинцов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Марат ", surname: "Кириллов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Яков ", surname: "Ковальчук", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Адам ", surname: "Дьячков", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Леопольд ", surname: "Линник", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Чеслав ", surname: "Гончар", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Роман ", surname: "Предыбайло", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Бронислав ", surname: "Доронин", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Зиновий ", surname: "Сазонов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Гавриил ", surname: "Зиновьев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Аким ", surname: "Стрелков", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Бронислав ", surname: "Хохлов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Герман ", surname: "Ерёменко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Остап ", surname: "Уваров", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Кир ", surname: "Панфилов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Йозеф ", surname: "Сирко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Денис ", surname: "Кириленко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Жерар ", surname: "Комаров", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Болеслав ", surname: "Калинин", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Чеслав ", surname: "Дзюба", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Устин ", surname: "Алексеев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Леопольд ", surname: "Дидовец", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Игорь ", surname: "Острожский", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Артур ", surname: "Гриневская", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Цезарь ", surname: "Негода", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Пётр ", surname: "Лазарев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Бронислав ", surname: "Цветков", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Эрик ", surname: "Волков", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Шарль ", surname: "Корнилов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Йозеф ", surname: "Многогрешный", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Устин ", surname: "Беляков", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Тимур ", surname: "Бобров", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Нестор ", surname: "Гаврилов", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Артур ", surname: "Киселёв", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Эрик ", surname: "Крюков", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Давид ", surname: "Тарасюк", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Емельян ", surname: "Назаров", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Никодим ", surname: "Сысоев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Йосеф ", surname: "Горобчук", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Дмитрий ", surname: "Павленко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Георгий ", surname: "Таранец", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Жигер ", surname: "Лаврентьев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Бронислав ", surname: "Пасичник", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Йозеф ", surname: "Захаров", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Спартак ", surname: "Кличко", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Йошка ", surname: "Медведев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Герасим", surname: "Алексеев", avatar: UIImage(named: "maleAvatar")!, images: imagesList))
        friends.append(User(name: "Флорентина ", surname: "Жукова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Искра ", surname: "Рыбакова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Таисия ", surname: "Федункив", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Тамара ", surname: "Тимошенко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Клавдия ", surname: "Владимирова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Дарья ", surname: "Исаева", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Лариса ", surname: "Куликова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Флорентина ", surname: "Хохлова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Валерия ", surname: "Червона", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Чилита ", surname: "Абрамова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Мальвина ", surname: "Абрамова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Дина ", surname: "Михеева", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Полина ", surname: "Трофимова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Шанетта ", surname: "Турова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Дарья ", surname: "Суворова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Маргарита ", surname: "Цветкова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Федосья ", surname: "Ковальчук", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Лидия ", surname: "Майборода", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Гелена ", surname: "Красильникова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Лада ", surname: "Острожска", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Йосифа ", surname: "Яковенко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Анфиса ", surname: "Колесник", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Кристина ", surname: "Романенко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Татьяна ", surname: "Ермакова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Клара ", surname: "Павленко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Береслава ", surname: "Гордеева", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Анастасия ", surname: "Полищук", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Лариса ", surname: "Мельникова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Раиса ", surname: "Зварыч", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Диана ", surname: "Андрусейко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Ульяна ", surname: "Батейко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Эсмеральда ", surname: "Сыпченко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Федосья ", surname: "Фомина", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Фаина ", surname: "Баранова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Йоханна ", surname: "Савельева", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Таисия ", surname: "Скоропадска", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Люся ", surname: "Маркова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Жанна ", surname: "Пахомова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Софья ", surname: "Молчанова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Кристина ", surname: "Негода", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Алиса ", surname: "Рогова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Оксана ", surname: "Андрусейко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Нина ", surname: "Никифорова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Инесса ", surname: "Соболева", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Йана ", surname: "Михайлова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Инна ", surname: "Бородай", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Чара ", surname: "Зиновьева", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Фаина ", surname: "Стрелкова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Берта ", surname: "Котовска", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Рената ", surname: "Лебедева", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Маргарита ", surname: "Дорофеева", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Олеся ", surname: "Пономаренко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Яна ", surname: "Коновалова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Изабелла ", surname: "Мухина", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Люся ", surname: "Сыпченко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Юзефа ", surname: "Тарасюк", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Зоя ", surname: "Маслова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Йосифа ", surname: "Воронова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Цветелина ", surname: "Навальна", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Устинья ", surname: "Никифорова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Устинья ", surname: "Линник", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Кристина ", surname: "Недбайло", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Ядвига ", surname: "Маслова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Регина ", surname: "Иващенко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Чилита ", surname: "Борисова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Эмма ", surname: "Гайчук", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Лариса ", surname: "Филатова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Доминика ", surname: "Гончар", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Изабелла ", surname: "Дидовец", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Шарлота ", surname: "Егорова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Рената ", surname: "Смирнова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Эльза ", surname: "Посидайло", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Чеслава ", surname: "Блинова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Тамара ", surname: "Архипова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Флорентина ", surname: "Сафонова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Клавдия ", surname: "Батейко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Лидия ", surname: "Иванив", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Шанетта ", surname: "Зайцева", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Алина ", surname: "Князева", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Валерия ", surname: "Потапова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Диана ", surname: "Новикова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Глория ", surname: "Панфилова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Бронислава ", surname: "Белозёрова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Федосья ", surname: "Королёва", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Цвета ", surname: "Рыбакова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Жаклин ", surname: "Громова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Ульяна ", surname: "Фролова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Харита ", surname: "Забужко", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Йоони ", surname: "Доронина", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Юзефа ", surname: "Бердник", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Раиса ", surname: "Дзюба", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Федосья ", surname: "Новикова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Зоя ", surname: "Александрова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Зоя ", surname: "Воронова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Клементина ", surname: "Хитрук", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Клавдия ", surname: "Ларионова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Октябрина ", surname: "Степанова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Лидия ", surname: "Шамрыло", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
        friends.append(User(name: "Лидия", surname: "Кузнецова", avatar: UIImage(named: "femaleAvatar")!, images: imagesList))
    }

}
